/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as FilmsSlugRouteImport } from './routes/films.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/reviews': typeof ReviewsRoute
  '/submit': typeof SubmitRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/reviews': typeof ReviewsRoute
  '/submit': typeof SubmitRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discover': typeof DiscoverRoute
  '/reviews': typeof ReviewsRoute
  '/submit': typeof SubmitRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/discover' | '/reviews' | '/submit' | '/films/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/discover' | '/reviews' | '/submit' | '/films/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/discover'
    | '/reviews'
    | '/submit'
    | '/films/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DiscoverRoute: typeof DiscoverRoute
  ReviewsRoute: typeof ReviewsRoute
  SubmitRoute: typeof SubmitRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DiscoverRoute: DiscoverRoute,
  ReviewsRoute: ReviewsRoute,
  SubmitRoute: SubmitRoute,
  FilmsSlugRoute: FilmsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
